// Generated by fbsgen from p/ds/prk/p4
"use strict";
var _7 = require('../../');
var p4;
(function (p4_1) {
    var P444441;
    (function (P444441) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.P1.$create()
            };
        }
        P444441.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P444441.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.P1.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444441.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444441.$handle = $handle;
        P444441.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P444441 = p4_1.P444441 || (p4_1.P444441 = {}));
    var P444444;
    (function (P444444) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.P4.$create()
            };
        }
        P444444.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P444444.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.P4.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444444.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444444.$handle = $handle;
        P444444.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P444444 = p4_1.P444444 || (p4_1.P444444 = {}));
    var P444448;
    (function (P444448) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.P8.$create()
            };
        }
        P444448.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P444448.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.P8.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444448.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444448.$handle = $handle;
        P444448.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P444448 = p4_1.P444448 || (p4_1.P444448 = {}));
    var P44444D;
    (function (P44444D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.PD.$create()
            };
        }
        P44444D.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P44444D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.PD.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44444D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44444D.$handle = $handle;
        P44444D.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P44444D = p4_1.P44444D || (p4_1.P44444D = {}));
    var P44444K;
    (function (P44444K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.PK.$create()
            };
        }
        P44444K.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P44444K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.PK.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44444K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44444K.$handle = $handle;
        P44444K.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P44444K = p4_1.P44444K || (p4_1.P44444K = {}));
    var P44444S;
    (function (P44444S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                p4: 0,
                l: _7.ds.PS.$create()
            };
        }
        P44444S.$create = $create;
        function create(p0, p1, p2, p3, p4, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                p4: p4,
                l: l
            };
        }
        P44444S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.p4, _6 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5 != null)
                buf.push('"5":' + _5);
            if (_6)
                buf.push('"6":' + _7.ds.PS.$stringify(_6));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44444S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44444S.$handle = $handle;
        P44444S.$descriptor = {
            $fdf: ['1', '2', '3', '4', '5'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 6, m: 2, a: 0, $: 'p4', $n: 'TODO name for display' },
            '6': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                p4: 5,
                l: 6
            },
            $handle: $handle
        };
    })(P44444S = p4_1.P44444S || (p4_1.P44444S = {}));
    var P44441;
    (function (P44441) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.P1.$create()
            };
        }
        P44441.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P44441.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.P1.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44441.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44441.$handle = $handle;
        P44441.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P44441 = p4_1.P44441 || (p4_1.P44441 = {}));
    var P44444;
    (function (P44444) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.P4.$create()
            };
        }
        P44444.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P44444.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.P4.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44444.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44444.$handle = $handle;
        P44444.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P44444 = p4_1.P44444 || (p4_1.P44444 = {}));
    var P44448;
    (function (P44448) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.P8.$create()
            };
        }
        P44448.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P44448.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.P8.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44448.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44448.$handle = $handle;
        P44448.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P44448 = p4_1.P44448 || (p4_1.P44448 = {}));
    var P4444D;
    (function (P4444D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.PD.$create()
            };
        }
        P4444D.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P4444D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.PD.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4444D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4444D.$handle = $handle;
        P4444D.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P4444D = p4_1.P4444D || (p4_1.P4444D = {}));
    var P4444K;
    (function (P4444K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.PK.$create()
            };
        }
        P4444K.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P4444K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.PK.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4444K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4444K.$handle = $handle;
        P4444K.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P4444K = p4_1.P4444K || (p4_1.P4444K = {}));
    var P4444S;
    (function (P4444S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                p3: 0,
                l: _7.ds.PS.$create()
            };
        }
        P4444S.$create = $create;
        function create(p0, p1, p2, p3, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                p3: p3,
                l: l
            };
        }
        P4444S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.p3, _5 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4 != null)
                buf.push('"4":' + _4);
            if (_5)
                buf.push('"5":' + _7.ds.PS.$stringify(_5));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4444S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4444S.$handle = $handle;
        P4444S.$descriptor = {
            $fdf: ['1', '2', '3', '4'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 6, m: 2, a: 0, $: 'p3', $n: 'TODO name for display' },
            '5': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                p3: 4,
                l: 5
            },
            $handle: $handle
        };
    })(P4444S = p4_1.P4444S || (p4_1.P4444S = {}));
    var P4441;
    (function (P4441) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.P1.$create()
            };
        }
        P4441.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P4441.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.P1.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4441.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4441.$handle = $handle;
        P4441.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P4441 = p4_1.P4441 || (p4_1.P4441 = {}));
    var P4444;
    (function (P4444) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.P4.$create()
            };
        }
        P4444.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P4444.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.P4.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4444.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4444.$handle = $handle;
        P4444.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P4444 = p4_1.P4444 || (p4_1.P4444 = {}));
    var P4448;
    (function (P4448) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.P8.$create()
            };
        }
        P4448.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P4448.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.P8.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4448.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4448.$handle = $handle;
        P4448.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P4448 = p4_1.P4448 || (p4_1.P4448 = {}));
    var P444D;
    (function (P444D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.PD.$create()
            };
        }
        P444D.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P444D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.PD.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444D.$handle = $handle;
        P444D.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P444D = p4_1.P444D || (p4_1.P444D = {}));
    var P444K;
    (function (P444K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.PK.$create()
            };
        }
        P444K.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P444K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.PK.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444K.$handle = $handle;
        P444K.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P444K = p4_1.P444K || (p4_1.P444K = {}));
    var P444S;
    (function (P444S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                p2: 0,
                l: _7.ds.PS.$create()
            };
        }
        P444S.$create = $create;
        function create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        P444S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + _7.ds.PS.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444S.$handle = $handle;
        P444S.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 6, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(P444S = p4_1.P444S || (p4_1.P444S = {}));
    var P411;
    (function (P411) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P1.$create()
            };
        }
        P411.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P411.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P411.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P411.$handle = $handle;
        P411.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P411 = p4_1.P411 || (p4_1.P411 = {}));
    var P414;
    (function (P414) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P4.$create()
            };
        }
        P414.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P414.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P414.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P414.$handle = $handle;
        P414.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P414 = p4_1.P414 || (p4_1.P414 = {}));
    var P418;
    (function (P418) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P8.$create()
            };
        }
        P418.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P418.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P418.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P418.$handle = $handle;
        P418.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P418 = p4_1.P418 || (p4_1.P418 = {}));
    var P41D;
    (function (P41D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PD.$create()
            };
        }
        P41D.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P41D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P41D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P41D.$handle = $handle;
        P41D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P41D = p4_1.P41D || (p4_1.P41D = {}));
    var P41K;
    (function (P41K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PK.$create()
            };
        }
        P41K.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P41K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P41K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P41K.$handle = $handle;
        P41K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P41K = p4_1.P41K || (p4_1.P41K = {}));
    var P41S;
    (function (P41S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PS.$create()
            };
        }
        P41S.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P41S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P41S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P41S.$handle = $handle;
        P41S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P41S = p4_1.P41S || (p4_1.P41S = {}));
    var P481;
    (function (P481) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P1.$create()
            };
        }
        P481.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P481.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P481.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P481.$handle = $handle;
        P481.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P481 = p4_1.P481 || (p4_1.P481 = {}));
    var P484;
    (function (P484) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P4.$create()
            };
        }
        P484.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P484.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P484.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P484.$handle = $handle;
        P484.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P484 = p4_1.P484 || (p4_1.P484 = {}));
    var P488;
    (function (P488) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P8.$create()
            };
        }
        P488.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P488.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P488.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P488.$handle = $handle;
        P488.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P488 = p4_1.P488 || (p4_1.P488 = {}));
    var P48D;
    (function (P48D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PD.$create()
            };
        }
        P48D.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P48D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P48D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P48D.$handle = $handle;
        P48D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P48D = p4_1.P48D || (p4_1.P48D = {}));
    var P48K;
    (function (P48K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PK.$create()
            };
        }
        P48K.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P48K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P48K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P48K.$handle = $handle;
        P48K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P48K = p4_1.P48K || (p4_1.P48K = {}));
    var P48S;
    (function (P48S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PS.$create()
            };
        }
        P48S.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P48S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P48S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P48S.$handle = $handle;
        P48S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P48S = p4_1.P48S || (p4_1.P48S = {}));
    var P4D1;
    (function (P4D1) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P1.$create()
            };
        }
        P4D1.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4D1.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4D1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4D1.$handle = $handle;
        P4D1.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4D1 = p4_1.P4D1 || (p4_1.P4D1 = {}));
    var P4D4;
    (function (P4D4) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P4.$create()
            };
        }
        P4D4.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4D4.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4D4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4D4.$handle = $handle;
        P4D4.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4D4 = p4_1.P4D4 || (p4_1.P4D4 = {}));
    var P4D8;
    (function (P4D8) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P8.$create()
            };
        }
        P4D8.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4D8.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4D8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4D8.$handle = $handle;
        P4D8.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4D8 = p4_1.P4D8 || (p4_1.P4D8 = {}));
    var P4DD;
    (function (P4DD) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PD.$create()
            };
        }
        P4DD.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4DD.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4DD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4DD.$handle = $handle;
        P4DD.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4DD = p4_1.P4DD || (p4_1.P4DD = {}));
    var P4DK;
    (function (P4DK) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PK.$create()
            };
        }
        P4DK.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4DK.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4DK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4DK.$handle = $handle;
        P4DK.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4DK = p4_1.P4DK || (p4_1.P4DK = {}));
    var P4DS;
    (function (P4DS) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PS.$create()
            };
        }
        P4DS.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4DS.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4DS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4DS.$handle = $handle;
        P4DS.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4DS = p4_1.P4DS || (p4_1.P4DS = {}));
    var P4K1;
    (function (P4K1) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P1.$create()
            };
        }
        P4K1.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4K1.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4K1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4K1.$handle = $handle;
        P4K1.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4K1 = p4_1.P4K1 || (p4_1.P4K1 = {}));
    var P4K4;
    (function (P4K4) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P4.$create()
            };
        }
        P4K4.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4K4.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4K4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4K4.$handle = $handle;
        P4K4.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4K4 = p4_1.P4K4 || (p4_1.P4K4 = {}));
    var P4K8;
    (function (P4K8) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P8.$create()
            };
        }
        P4K8.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4K8.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4K8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4K8.$handle = $handle;
        P4K8.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4K8 = p4_1.P4K8 || (p4_1.P4K8 = {}));
    var P4KD;
    (function (P4KD) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PD.$create()
            };
        }
        P4KD.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4KD.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4KD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4KD.$handle = $handle;
        P4KD.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4KD = p4_1.P4KD || (p4_1.P4KD = {}));
    var P4KK;
    (function (P4KK) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PK.$create()
            };
        }
        P4KK.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4KK.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4KK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4KK.$handle = $handle;
        P4KK.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4KK = p4_1.P4KK || (p4_1.P4KK = {}));
    var P4KS;
    (function (P4KS) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PS.$create()
            };
        }
        P4KS.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4KS.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4KS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4KS.$handle = $handle;
        P4KS.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4KS = p4_1.P4KS || (p4_1.P4KS = {}));
    var P441;
    (function (P441) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P1.$create()
            };
        }
        P441.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P441.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P441.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P441.$handle = $handle;
        P441.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P441 = p4_1.P441 || (p4_1.P441 = {}));
    var P444;
    (function (P444) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P4.$create()
            };
        }
        P444.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P444.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P444.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P444.$handle = $handle;
        P444.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P444 = p4_1.P444 || (p4_1.P444 = {}));
    var P448;
    (function (P448) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.P8.$create()
            };
        }
        P448.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P448.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P448.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P448.$handle = $handle;
        P448.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P448 = p4_1.P448 || (p4_1.P448 = {}));
    var P44D;
    (function (P44D) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PD.$create()
            };
        }
        P44D.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P44D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44D.$handle = $handle;
        P44D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P44D = p4_1.P44D || (p4_1.P44D = {}));
    var P44K;
    (function (P44K) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PK.$create()
            };
        }
        P44K.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P44K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44K.$handle = $handle;
        P44K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P44K = p4_1.P44K || (p4_1.P44K = {}));
    var P44S;
    (function (P44S) {
        function $create() {
            return {
                p0: 0,
                p1: 0,
                l: _7.ds.PS.$create()
            };
        }
        P44S.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P44S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44S.$handle = $handle;
        P44S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P44S = p4_1.P44S || (p4_1.P44S = {}));
    var P4S1;
    (function (P4S1) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P1.$create()
            };
        }
        P4S1.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4S1.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4S1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4S1.$handle = $handle;
        P4S1.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4S1 = p4_1.P4S1 || (p4_1.P4S1 = {}));
    var P4S4;
    (function (P4S4) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P4.$create()
            };
        }
        P4S4.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4S4.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4S4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4S4.$handle = $handle;
        P4S4.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4S4 = p4_1.P4S4 || (p4_1.P4S4 = {}));
    var P4S8;
    (function (P4S8) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.P8.$create()
            };
        }
        P4S8.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4S8.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4S8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4S8.$handle = $handle;
        P4S8.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4S8 = p4_1.P4S8 || (p4_1.P4S8 = {}));
    var P4SD;
    (function (P4SD) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PD.$create()
            };
        }
        P4SD.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4SD.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4SD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4SD.$handle = $handle;
        P4SD.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4SD = p4_1.P4SD || (p4_1.P4SD = {}));
    var P4SK;
    (function (P4SK) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PK.$create()
            };
        }
        P4SK.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4SK.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4SK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4SK.$handle = $handle;
        P4SK.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4SK = p4_1.P4SK || (p4_1.P4SK = {}));
    var P4SS;
    (function (P4SS) {
        function $create() {
            return {
                p0: 0,
                p1: "",
                l: _7.ds.PS.$create()
            };
        }
        P4SS.$create = $create;
        function create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P4SS.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + _7.ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4SS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4SS.$handle = $handle;
        P4SS.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(P4SS = p4_1.P4SS || (p4_1.P4SS = {}));
    var P41;
    (function (P41) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.P1.$create()
            };
        }
        P41.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P41.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.P1.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P41.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P41.$handle = $handle;
        P41.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P1.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P41 = p4_1.P41 || (p4_1.P41 = {}));
    var P44;
    (function (P44) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.P4.$create()
            };
        }
        P44.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P44.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.P4.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P44.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P44.$handle = $handle;
        P44.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P4.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P44 = p4_1.P44 || (p4_1.P44 = {}));
    var P48;
    (function (P48) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.P8.$create()
            };
        }
        P48.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P48.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.P8.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P48.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P48.$handle = $handle;
        P48.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.P8.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P48 = p4_1.P48 || (p4_1.P48 = {}));
    var P4D;
    (function (P4D) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.PD.$create()
            };
        }
        P4D.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P4D.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.PD.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4D.$handle = $handle;
        P4D.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PD.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P4D = p4_1.P4D || (p4_1.P4D = {}));
    var P4K;
    (function (P4K) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.PK.$create()
            };
        }
        P4K.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P4K.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.PK.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4K.$handle = $handle;
        P4K.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PK.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P4K = p4_1.P4K || (p4_1.P4K = {}));
    var P4S;
    (function (P4S) {
        function $create() {
            return {
                p0: 0,
                l: _7.ds.PS.$create()
            };
        }
        P4S.$create = $create;
        function create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P4S.create = create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + _7.ds.PS.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4S.$handle = $handle;
        P4S.$descriptor = {
            $fdf: ['1'],
            '1': { t: 6, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: _7.ds.PS.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(P4S = p4_1.P4S || (p4_1.P4S = {}));
})(p4 = exports.p4 || (exports.p4 = {}));
//# sourceMappingURL=index.js.map