// Generated by fbsgen from p/ds
"use strict";
var _5 = require('../');
var ds;
(function (ds) {
    var ParamId;
    (function (ParamId) {
        function $create() {
            return {
                id: 0
            };
        }
        ParamId.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.id;
            if (_1 != null)
                buf.push('"1":' + _1);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamId.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        ParamId.$handle = $handle;
        ParamId.$descriptor = {
            '1': { t: 10, m: 2, a: 0, $: 'id', $n: 'TODO name for display' },
            $: {
                id: 1
            },
            $handle: $handle
        };
    })(ParamId = ds.ParamId || (ds.ParamId = {}));
    var ParamKey;
    (function (ParamKey) {
        function $create() {
            return {
                key: "",
                parentKey: ""
            };
        }
        ParamKey.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.key, _2 = obj.parentKey;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamKey.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        ParamKey.$handle = $handle;
        ParamKey.$descriptor = {
            '1': { t: 2, m: 2, a: 0, $: 'key', $n: 'TODO name for display' },
            '2': { t: 2, m: 1, a: 0, $: 'parentKey', $n: 'TODO name for display' },
            $: {
                key: 1,
                parentKey: 2
            },
            $handle: $handle
        };
    })(ParamKey = ds.ParamKey || (ds.ParamKey = {}));
    var ParamUpdate;
    (function (ParamUpdate) {
        function $create() {
            return {
                key: "",
                mc: _5.MultiCAS.$create(),
                id: 0
            };
        }
        ParamUpdate.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.key, _2 = obj.mc, _3 = obj.id;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + _5.MultiCAS.$stringify(_2));
            if (_3 != null)
                buf.push('"3":' + _3);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamUpdate.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        ParamUpdate.$handle = $handle;
        ParamUpdate.$descriptor = {
            '1': { t: 2, m: 2, a: 0, $: 'key', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'mc', $n: 'TODO name for display', d: _5.MultiCAS.$descriptor },
            '3': { t: 10, m: 1, a: 0, $: 'id', $n: 'TODO name for display' },
            $: {
                key: 1,
                mc: 2,
                id: 3
            },
            $handle: $handle
        };
    })(ParamUpdate = ds.ParamUpdate || (ds.ParamUpdate = {}));
    var ParamRangeKey;
    (function (ParamRangeKey) {
        function $create() {
            return {
                desc: false,
                limit: 0,
                startKey: "",
                parentKey: ""
            };
        }
        ParamRangeKey.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.desc, _2 = obj.limit, _3 = obj.startKey, _4 = obj.parentKey;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":"' + _4 + '"');
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamRangeKey.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        ParamRangeKey.$handle = $handle;
        ParamRangeKey.$descriptor = {
            '1': { t: 1, m: 2, a: 0, $: 'desc', $n: 'TODO name for display' },
            '2': { t: 6, m: 1, a: 0, $: 'limit', $n: 'TODO name for display' },
            '3': { t: 2, m: 1, a: 0, $: 'startKey', $n: 'TODO name for display' },
            '4': { t: 2, m: 1, a: 0, $: 'parentKey', $n: 'TODO name for display' },
            $: {
                desc: 1,
                limit: 2,
                startKey: 3,
                parentKey: 4
            },
            $handle: $handle
        };
    })(ParamRangeKey = ds.ParamRangeKey || (ds.ParamRangeKey = {}));
    var ACResult;
    (function (ACResult) {
        function $create() {
            return {
                name: "",
                value: "",
                id: 0
            };
        }
        ACResult.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.name, _2 = obj.value, _3 = obj.id;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3 != null)
                buf.push('"3":' + _3);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ACResult.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        ACResult.$handle = $handle;
        ACResult.$descriptor = {
            '1': { t: 3, m: 2, a: 0, $: 'name', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '3': { t: 10, m: 1, a: 0, $: 'id', $n: 'TODO name for display' },
            $: {
                name: 1,
                value: 2,
                id: 3
            },
            $handle: $handle
        };
    })(ACResult = ds.ACResult || (ds.ACResult = {}));
    var P1;
    (function (P1) {
        function $create() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$create()
            };
        }
        P1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P1.$handle = $handle;
        P1.$descriptor = {
            '1': { t: 8, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 8, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 8, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(P1 = ds.P1 || (ds.P1 = {}));
    var P4;
    (function (P4) {
        function $create() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$create()
            };
        }
        P4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P4.$handle = $handle;
        P4.$descriptor = {
            '1': { t: 6, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 6, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 6, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(P4 = ds.P4 || (ds.P4 = {}));
    var P8;
    (function (P8) {
        function $create() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$create()
            };
        }
        P8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        P8.$handle = $handle;
        P8.$descriptor = {
            '1': { t: 11, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 11, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 11, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(P8 = ds.P8 || (ds.P8 = {}));
    var PD;
    (function (PD) {
        function $create() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$create()
            };
        }
        PD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PD.$handle = $handle;
        PD.$descriptor = {
            '1': { t: 11, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 11, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 11, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(PD = ds.PD || (ds.PD = {}));
    var PB;
    (function (PB) {
        function $create() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$create()
            };
        }
        PB.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PB.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PB.$handle = $handle;
        PB.$descriptor = {
            '1': { t: 2, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 2, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 2, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(PB = ds.PB || (ds.PB = {}));
    var PK;
    (function (PK) {
        function $create() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$create()
            };
        }
        PK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PK.$handle = $handle;
        PK.$descriptor = {
            '1': { t: 2, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 2, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 2, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(PK = ds.PK || (ds.PK = {}));
    var PS;
    (function (PS) {
        function $create() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$create()
            };
        }
        PS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS.$handle = $handle;
        PS.$descriptor = {
            '1': { t: 3, m: 2, a: 0, $: 'value', $n: 'TODO name for display' },
            '2': { t: 3, m: 1, a: 0, $: 'end', $n: 'TODO name for display' },
            '3': { t: 3, m: 1, a: 0, $: 'pgstart', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'prk', $n: 'TODO name for display', d: ParamRangeKey.$descriptor },
            $: {
                value: 1,
                end: 2,
                pgstart: 3,
                prk: 4
            },
            $handle: $handle
        };
    })(PS = ds.PS || (ds.PS = {}));
})(ds = exports.ds || (exports.ds = {}));
//# sourceMappingURL=index.js.map