// Generated by fbsgen from p/ds
import { $change } from '../';
import mc_ from './mc';
export var ds;
(function (ds) {
    ds.MultiCAS = mc_;
    var ParamId;
    (function (ParamId) {
        function $create(id) {
            return {
                id: id
            };
        }
        ParamId.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.id;
            if (_1 != null)
                buf.push('"1":' + _1);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamId.$stringify = $stringify;
        function $createObservable() {
            return {
                id: 0,
                _: null //, $d: null
            };
        }
        ParamId.$createObservable = $createObservable;
        ParamId.$descriptor = {
            '1': { _: 1, t: 10, m: 2, a: 0, $: 'id', $n: 'Id' },
            $: {
                id: '1'
            }, $new: $createObservable, $change: $change
        };
    })(ParamId = ds.ParamId || (ds.ParamId = {}));
    var ParamKey;
    (function (ParamKey) {
        function $create(key, parentKey) {
            return {
                key: key,
                parentKey: parentKey
            };
        }
        ParamKey.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.key, _2 = obj.parentKey;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamKey.$stringify = $stringify;
        function $createObservable() {
            return {
                key: "",
                parentKey: "",
                _: null //, $d: null
            };
        }
        ParamKey.$createObservable = $createObservable;
        ParamKey.$descriptor = {
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'key', $n: 'Key' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'parentKey', $n: 'Parent Key' },
            $: {
                key: '1',
                parentKey: '2'
            }, $new: $createObservable, $change: $change
        };
    })(ParamKey = ds.ParamKey || (ds.ParamKey = {}));
    var ParamUpdate;
    (function (ParamUpdate) {
        function $create(key, mc, id) {
            return {
                key: key,
                mc: mc,
                id: id
            };
        }
        ParamUpdate.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.key, _2 = obj.mc, _3 = obj.id;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.MultiCAS.$stringify(_2));
            if (_3 != null)
                buf.push('"3":' + _3);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamUpdate.$stringify = $stringify;
        function $createObservable() {
            return {
                key: "",
                mc: ds.MultiCAS.$createObservable(),
                id: 0,
                _: null //, $d: null
            };
        }
        ParamUpdate.$createObservable = $createObservable;
        ParamUpdate.$descriptor = {
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'key', $n: 'Key' },
            '2': { _: 2, t: 0, m: 2, a: 0, $: 'mc', $n: 'Mc', d_fn: function () { return ds.MultiCAS.$descriptor; } },
            '3': { _: 3, t: 10, m: 1, a: 0, $: 'id', $n: 'Id' },
            $: {
                key: '1',
                mc: '2',
                id: '3'
            }, $new: $createObservable, $change: $change
        };
    })(ParamUpdate = ds.ParamUpdate || (ds.ParamUpdate = {}));
    var ParamRangeKey;
    (function (ParamRangeKey) {
        function $create(desc, limit, startKey, parentKey) {
            return {
                desc: desc,
                limit: limit,
                startKey: startKey,
                parentKey: parentKey
            };
        }
        ParamRangeKey.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.desc, _2 = obj.limit, _3 = obj.startKey, _4 = obj.parentKey;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":"' + _4 + '"');
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ParamRangeKey.$stringify = $stringify;
        function $createObservable() {
            return {
                desc: false,
                limit: 0,
                startKey: "",
                parentKey: "",
                _: null //, $d: null
            };
        }
        ParamRangeKey.$createObservable = $createObservable;
        ParamRangeKey.$descriptor = {
            '1': { _: 1, t: 1, m: 2, a: 0, $: 'desc', $n: 'Desc' },
            '2': { _: 2, t: 6, m: 1, a: 0, $: 'limit', $n: 'Limit' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'startKey', $n: 'Start Key' },
            '4': { _: 4, t: 2, m: 1, a: 0, $: 'parentKey', $n: 'Parent Key' },
            $: {
                desc: '1',
                limit: '2',
                startKey: '3',
                parentKey: '4'
            }, $new: $createObservable, $change: $change
        };
    })(ParamRangeKey = ds.ParamRangeKey || (ds.ParamRangeKey = {}));
    var ACResult;
    (function (ACResult) {
        function $create(name, value, id) {
            return {
                name: name,
                value: value,
                id: id
            };
        }
        ACResult.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.name, _2 = obj.value, _3 = obj.id;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3 != null)
                buf.push('"3":' + _3);
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        ACResult.$stringify = $stringify;
        function $createObservable() {
            return {
                name: "",
                value: "",
                id: 0,
                _: null //, $d: null
            };
        }
        ACResult.$createObservable = $createObservable;
        ACResult.$descriptor = {
            '1': { _: 1, t: 3, m: 2, a: 0, $: 'name', $n: 'Name' },
            '2': { _: 2, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '3': { _: 3, t: 10, m: 1, a: 0, $: 'id', $n: 'Id' },
            $: {
                name: '1',
                value: '2',
                id: '3'
            }, $new: $createObservable, $change: $change
        };
    })(ACResult = ds.ACResult || (ds.ACResult = {}));
    var P1;
    (function (P1) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        P1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P1.$stringify = $stringify;
        function $createObservable() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        P1.$createObservable = $createObservable;
        P1.$descriptor = {
            '1': { _: 1, t: 8, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 8, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 8, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(P1 = ds.P1 || (ds.P1 = {}));
    var P4;
    (function (P4) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        P4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P4.$stringify = $stringify;
        function $createObservable() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        P4.$createObservable = $createObservable;
        P4.$descriptor = {
            '1': { _: 1, t: 6, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 6, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 6, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(P4 = ds.P4 || (ds.P4 = {}));
    var P8;
    (function (P8) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        P8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8.$stringify = $stringify;
        function $createObservable() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        P8.$createObservable = $createObservable;
        P8.$descriptor = {
            '1': { _: 1, t: 11, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 11, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 11, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(P8 = ds.P8 || (ds.P8 = {}));
    var PD;
    (function (PD) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        PD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PD.$stringify = $stringify;
        function $createObservable() {
            return {
                value: 0,
                end: 0,
                pgstart: 0,
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        PD.$createObservable = $createObservable;
        PD.$descriptor = {
            '1': { _: 1, t: 11, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 11, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 11, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(PD = ds.PD || (ds.PD = {}));
    var PB;
    (function (PB) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        PB.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PB.$stringify = $stringify;
        function $createObservable() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        PB.$createObservable = $createObservable;
        PB.$descriptor = {
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(PB = ds.PB || (ds.PB = {}));
    var PK;
    (function (PK) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        PK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PK.$stringify = $stringify;
        function $createObservable() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        PK.$createObservable = $createObservable;
        PK.$descriptor = {
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(PK = ds.PK || (ds.PK = {}));
    var PS;
    (function (PS) {
        function $create(value, prk, end, pgstart) {
            return {
                value: value,
                end: end,
                pgstart: pgstart,
                prk: prk
            };
        }
        PS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.value, _2 = obj.end, _3 = obj.pgstart, _4 = obj.prk;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":"' + _3 + '"');
            if (_4)
                buf.push('"4":' + ParamRangeKey.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS.$stringify = $stringify;
        function $createObservable() {
            return {
                value: "",
                end: "",
                pgstart: "",
                prk: ParamRangeKey.$createObservable(),
                _: null //, $d: null
            };
        }
        PS.$createObservable = $createObservable;
        PS.$descriptor = {
            '1': { _: 1, t: 3, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 3, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 3, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$descriptor; } },
            $: {
                value: '1',
                end: '2',
                pgstart: '3',
                prk: '4'
            }, $new: $createObservable, $change: $change
        };
    })(PS = ds.PS || (ds.PS = {}));
})(ds || (ds = {}));
//# sourceMappingURL=index.js.map