// Generated by fbsgen from p/ds/prk/p8
import { ds } from '../../';
export var p8;
(function (p8) {
    var P881;
    (function (P881) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P881.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P881.$stringify = $stringify;
    })(P881 = p8.P881 || (p8.P881 = {}));
    var P884;
    (function (P884) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P884.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P884.$stringify = $stringify;
    })(P884 = p8.P884 || (p8.P884 = {}));
    var P888;
    (function (P888) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P888.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P888.$stringify = $stringify;
    })(P888 = p8.P888 || (p8.P888 = {}));
    var P88D;
    (function (P88D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P88D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P88D.$stringify = $stringify;
    })(P88D = p8.P88D || (p8.P88D = {}));
    var P88K;
    (function (P88K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P88K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P88K.$stringify = $stringify;
    })(P88K = p8.P88K || (p8.P88K = {}));
    var P88S;
    (function (P88S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P88S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P88S.$stringify = $stringify;
    })(P88S = p8.P88S || (p8.P88S = {}));
    var P811;
    (function (P811) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P811.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P811.$stringify = $stringify;
    })(P811 = p8.P811 || (p8.P811 = {}));
    var P814;
    (function (P814) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P814.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P814.$stringify = $stringify;
    })(P814 = p8.P814 || (p8.P814 = {}));
    var P818;
    (function (P818) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P818.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P818.$stringify = $stringify;
    })(P818 = p8.P818 || (p8.P818 = {}));
    var P81D;
    (function (P81D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P81D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P81D.$stringify = $stringify;
    })(P81D = p8.P81D || (p8.P81D = {}));
    var P81K;
    (function (P81K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P81K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P81K.$stringify = $stringify;
    })(P81K = p8.P81K || (p8.P81K = {}));
    var P81S;
    (function (P81S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P81S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P81S.$stringify = $stringify;
    })(P81S = p8.P81S || (p8.P81S = {}));
    var P841;
    (function (P841) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P841.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P841.$stringify = $stringify;
    })(P841 = p8.P841 || (p8.P841 = {}));
    var P844;
    (function (P844) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P844.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P844.$stringify = $stringify;
    })(P844 = p8.P844 || (p8.P844 = {}));
    var P848;
    (function (P848) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P848.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P848.$stringify = $stringify;
    })(P848 = p8.P848 || (p8.P848 = {}));
    var P84D;
    (function (P84D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P84D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P84D.$stringify = $stringify;
    })(P84D = p8.P84D || (p8.P84D = {}));
    var P84K;
    (function (P84K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P84K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P84K.$stringify = $stringify;
    })(P84K = p8.P84K || (p8.P84K = {}));
    var P84S;
    (function (P84S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P84S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P84S.$stringify = $stringify;
    })(P84S = p8.P84S || (p8.P84S = {}));
    var P81;
    (function (P81) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P81.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.P1.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P81.$stringify = $stringify;
    })(P81 = p8.P81 || (p8.P81 = {}));
    var P84;
    (function (P84) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P84.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.P4.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P84.$stringify = $stringify;
    })(P84 = p8.P84 || (p8.P84 = {}));
    var P88;
    (function (P88) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P88.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.P8.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P88.$stringify = $stringify;
    })(P88 = p8.P88 || (p8.P88 = {}));
    var P8D;
    (function (P8D) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P8D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.PD.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8D.$stringify = $stringify;
    })(P8D = p8.P8D || (p8.P8D = {}));
    var P8K;
    (function (P8K) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P8K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.PK.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8K.$stringify = $stringify;
    })(P8K = p8.P8K || (p8.P8K = {}));
    var P8S;
    (function (P8S) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        P8S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":' + ds.PS.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8S.$stringify = $stringify;
    })(P8S = p8.P8S || (p8.P8S = {}));
    var P8S1;
    (function (P8S1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8S1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8S1.$stringify = $stringify;
    })(P8S1 = p8.P8S1 || (p8.P8S1 = {}));
    var P8S4;
    (function (P8S4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8S4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8S4.$stringify = $stringify;
    })(P8S4 = p8.P8S4 || (p8.P8S4 = {}));
    var P8S8;
    (function (P8S8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8S8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8S8.$stringify = $stringify;
    })(P8S8 = p8.P8S8 || (p8.P8S8 = {}));
    var P8SD;
    (function (P8SD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8SD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8SD.$stringify = $stringify;
    })(P8SD = p8.P8SD || (p8.P8SD = {}));
    var P8SK;
    (function (P8SK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8SK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8SK.$stringify = $stringify;
    })(P8SK = p8.P8SK || (p8.P8SK = {}));
    var P8SS;
    (function (P8SS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8SS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8SS.$stringify = $stringify;
    })(P8SS = p8.P8SS || (p8.P8SS = {}));
    var P8D1;
    (function (P8D1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8D1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8D1.$stringify = $stringify;
    })(P8D1 = p8.P8D1 || (p8.P8D1 = {}));
    var P8D4;
    (function (P8D4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8D4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8D4.$stringify = $stringify;
    })(P8D4 = p8.P8D4 || (p8.P8D4 = {}));
    var P8D8;
    (function (P8D8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8D8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8D8.$stringify = $stringify;
    })(P8D8 = p8.P8D8 || (p8.P8D8 = {}));
    var P8DD;
    (function (P8DD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8DD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8DD.$stringify = $stringify;
    })(P8DD = p8.P8DD || (p8.P8DD = {}));
    var P8DK;
    (function (P8DK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8DK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8DK.$stringify = $stringify;
    })(P8DK = p8.P8DK || (p8.P8DK = {}));
    var P8DS;
    (function (P8DS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8DS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8DS.$stringify = $stringify;
    })(P8DS = p8.P8DS || (p8.P8DS = {}));
    var P8K1;
    (function (P8K1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8K1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8K1.$stringify = $stringify;
    })(P8K1 = p8.P8K1 || (p8.P8K1 = {}));
    var P8K4;
    (function (P8K4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8K4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8K4.$stringify = $stringify;
    })(P8K4 = p8.P8K4 || (p8.P8K4 = {}));
    var P8K8;
    (function (P8K8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8K8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8K8.$stringify = $stringify;
    })(P8K8 = p8.P8K8 || (p8.P8K8 = {}));
    var P8KD;
    (function (P8KD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8KD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8KD.$stringify = $stringify;
    })(P8KD = p8.P8KD || (p8.P8KD = {}));
    var P8KK;
    (function (P8KK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8KK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8KK.$stringify = $stringify;
    })(P8KK = p8.P8KK || (p8.P8KK = {}));
    var P8KS;
    (function (P8KS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        P8KS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1 != null)
                buf.push('"1":' + _1);
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        P8KS.$stringify = $stringify;
    })(P8KS = p8.P8KS || (p8.P8KS = {}));
})(p8 || (p8 = {}));
//# sourceMappingURL=index.js.map