// Generated by fbsgen from p/ds/prk/ps
import { ds } from '../../';
export var ps;
(function (ps) {
    var PSK1;
    (function (PSK1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSK1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSK1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSK1.$handle = $handle;
        PSK1.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSK1 = ps.PSK1 || (ps.PSK1 = {}));
    var PSK4;
    (function (PSK4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSK4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSK4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSK4.$handle = $handle;
        PSK4.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSK4 = ps.PSK4 || (ps.PSK4 = {}));
    var PSK8;
    (function (PSK8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSK8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSK8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSK8.$handle = $handle;
        PSK8.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSK8 = ps.PSK8 || (ps.PSK8 = {}));
    var PSKD;
    (function (PSKD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSKD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSKD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSKD.$handle = $handle;
        PSKD.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSKD = ps.PSKD || (ps.PSKD = {}));
    var PSKK;
    (function (PSKK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSKK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSKK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSKK.$handle = $handle;
        PSKK.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSKK = ps.PSKK || (ps.PSKK = {}));
    var PSKS;
    (function (PSKS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSKS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSKS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSKS.$handle = $handle;
        PSKS.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 2, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSKS = ps.PSKS || (ps.PSKS = {}));
    var PS111;
    (function (PS111) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS111.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.P1.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS111.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS111.$handle = $handle;
        PS111.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS111 = ps.PS111 || (ps.PS111 = {}));
    var PS114;
    (function (PS114) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS114.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.P4.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS114.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS114.$handle = $handle;
        PS114.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS114 = ps.PS114 || (ps.PS114 = {}));
    var PS118;
    (function (PS118) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS118.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.P8.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS118.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS118.$handle = $handle;
        PS118.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS118 = ps.PS118 || (ps.PS118 = {}));
    var PS11D;
    (function (PS11D) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS11D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.PD.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS11D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS11D.$handle = $handle;
        PS11D.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS11D = ps.PS11D || (ps.PS11D = {}));
    var PS11K;
    (function (PS11K) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS11K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.PK.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS11K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS11K.$handle = $handle;
        PS11K.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS11K = ps.PS11K || (ps.PS11K = {}));
    var PS11S;
    (function (PS11S) {
        function $create(p0, p1, p2, l) {
            return {
                p0: p0,
                p1: p1,
                p2: p2,
                l: l
            };
        }
        PS11S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.p2, _4 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3 != null)
                buf.push('"3":' + _3);
            if (_4)
                buf.push('"4":' + ds.PS.$stringify(_4));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS11S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS11S.$handle = $handle;
        PS11S.$descriptor = {
            $fdf: ['1', '2', '3'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 8, m: 2, a: 0, $: 'p2', $n: 'TODO name for display' },
            '4': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                p2: 3,
                l: 4
            },
            $handle: $handle
        };
    })(PS11S = ps.PS11S || (ps.PS11S = {}));
    var PSD1;
    (function (PSD1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSD1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSD1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSD1.$handle = $handle;
        PSD1.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSD1 = ps.PSD1 || (ps.PSD1 = {}));
    var PSD4;
    (function (PSD4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSD4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSD4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSD4.$handle = $handle;
        PSD4.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSD4 = ps.PSD4 || (ps.PSD4 = {}));
    var PSD8;
    (function (PSD8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSD8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSD8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSD8.$handle = $handle;
        PSD8.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSD8 = ps.PSD8 || (ps.PSD8 = {}));
    var PSDD;
    (function (PSDD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSDD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSDD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSDD.$handle = $handle;
        PSDD.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSDD = ps.PSDD || (ps.PSDD = {}));
    var PSDK;
    (function (PSDK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSDK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSDK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSDK.$handle = $handle;
        PSDK.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSDK = ps.PSDK || (ps.PSDK = {}));
    var PSDS;
    (function (PSDS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSDS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSDS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSDS.$handle = $handle;
        PSDS.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSDS = ps.PSDS || (ps.PSDS = {}));
    var PS41;
    (function (PS41) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS41.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS41.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS41.$handle = $handle;
        PS41.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS41 = ps.PS41 || (ps.PS41 = {}));
    var PS44;
    (function (PS44) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS44.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS44.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS44.$handle = $handle;
        PS44.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS44 = ps.PS44 || (ps.PS44 = {}));
    var PS48;
    (function (PS48) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS48.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS48.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS48.$handle = $handle;
        PS48.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS48 = ps.PS48 || (ps.PS48 = {}));
    var PS4D;
    (function (PS4D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS4D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS4D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS4D.$handle = $handle;
        PS4D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS4D = ps.PS4D || (ps.PS4D = {}));
    var PS4K;
    (function (PS4K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS4K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS4K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS4K.$handle = $handle;
        PS4K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS4K = ps.PS4K || (ps.PS4K = {}));
    var PS4S;
    (function (PS4S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS4S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS4S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS4S.$handle = $handle;
        PS4S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 6, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS4S = ps.PS4S || (ps.PS4S = {}));
    var PSS1;
    (function (PSS1) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSS1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSS1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSS1.$handle = $handle;
        PSS1.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSS1 = ps.PSS1 || (ps.PSS1 = {}));
    var PSS4;
    (function (PSS4) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSS4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSS4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSS4.$handle = $handle;
        PSS4.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSS4 = ps.PSS4 || (ps.PSS4 = {}));
    var PSS8;
    (function (PSS8) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSS8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSS8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSS8.$handle = $handle;
        PSS8.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSS8 = ps.PSS8 || (ps.PSS8 = {}));
    var PSSD;
    (function (PSSD) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSSD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSSD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSSD.$handle = $handle;
        PSSD.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSSD = ps.PSSD || (ps.PSSD = {}));
    var PSSK;
    (function (PSSK) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSSK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSSK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSSK.$handle = $handle;
        PSSK.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSSK = ps.PSSK || (ps.PSSK = {}));
    var PSSS;
    (function (PSSS) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PSSS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":"' + _2 + '"');
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSSS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSSS.$handle = $handle;
        PSSS.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 3, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PSSS = ps.PSSS || (ps.PSSS = {}));
    var PS11;
    (function (PS11) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS11.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS11.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS11.$handle = $handle;
        PS11.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS11 = ps.PS11 || (ps.PS11 = {}));
    var PS14;
    (function (PS14) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS14.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS14.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS14.$handle = $handle;
        PS14.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS14 = ps.PS14 || (ps.PS14 = {}));
    var PS18;
    (function (PS18) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS18.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS18.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS18.$handle = $handle;
        PS18.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS18 = ps.PS18 || (ps.PS18 = {}));
    var PS1D;
    (function (PS1D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS1D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS1D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS1D.$handle = $handle;
        PS1D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS1D = ps.PS1D || (ps.PS1D = {}));
    var PS1K;
    (function (PS1K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS1K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS1K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS1K.$handle = $handle;
        PS1K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS1K = ps.PS1K || (ps.PS1K = {}));
    var PS1S;
    (function (PS1S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS1S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS1S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS1S.$handle = $handle;
        PS1S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 8, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS1S = ps.PS1S || (ps.PS1S = {}));
    var PS81;
    (function (PS81) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS81.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P1.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS81.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS81.$handle = $handle;
        PS81.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS81 = ps.PS81 || (ps.PS81 = {}));
    var PS84;
    (function (PS84) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS84.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P4.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS84.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS84.$handle = $handle;
        PS84.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS84 = ps.PS84 || (ps.PS84 = {}));
    var PS88;
    (function (PS88) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS88.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.P8.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS88.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS88.$handle = $handle;
        PS88.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS88 = ps.PS88 || (ps.PS88 = {}));
    var PS8D;
    (function (PS8D) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS8D.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PD.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS8D.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS8D.$handle = $handle;
        PS8D.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS8D = ps.PS8D || (ps.PS8D = {}));
    var PS8K;
    (function (PS8K) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS8K.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PK.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS8K.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS8K.$handle = $handle;
        PS8K.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS8K = ps.PS8K || (ps.PS8K = {}));
    var PS8S;
    (function (PS8S) {
        function $create(p0, p1, l) {
            return {
                p0: p0,
                p1: p1,
                l: l
            };
        }
        PS8S.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.p1, _3 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2 != null)
                buf.push('"2":' + _2);
            if (_3)
                buf.push('"3":' + ds.PS.$stringify(_3));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS8S.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS8S.$handle = $handle;
        PS8S.$descriptor = {
            $fdf: ['1', '2'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 11, m: 2, a: 0, $: 'p1', $n: 'TODO name for display' },
            '3': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                p1: 2,
                l: 3
            },
            $handle: $handle
        };
    })(PS8S = ps.PS8S || (ps.PS8S = {}));
    var PS1;
    (function (PS1) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PS1.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.P1.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS1.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS1.$handle = $handle;
        PS1.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P1.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PS1 = ps.PS1 || (ps.PS1 = {}));
    var PS4;
    (function (PS4) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PS4.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.P4.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS4.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS4.$handle = $handle;
        PS4.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P4.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PS4 = ps.PS4 || (ps.PS4 = {}));
    var PS8;
    (function (PS8) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PS8.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.P8.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PS8.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PS8.$handle = $handle;
        PS8.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.P8.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PS8 = ps.PS8 || (ps.PS8 = {}));
    var PSD;
    (function (PSD) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PSD.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.PD.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSD.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSD.$handle = $handle;
        PSD.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PD.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PSD = ps.PSD || (ps.PSD = {}));
    var PSK;
    (function (PSK) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PSK.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.PK.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSK.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSK.$handle = $handle;
        PSK.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PK.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PSK = ps.PSK || (ps.PSK = {}));
    var PSS;
    (function (PSS) {
        function $create(p0, l) {
            return {
                p0: p0,
                l: l
            };
        }
        PSS.$create = $create;
        function $stringify(obj) {
            var buf = [], _1 = obj.p0, _2 = obj.l;
            if (_1)
                buf.push('"1":"' + _1 + '"');
            if (_2)
                buf.push('"2":' + ds.PS.$stringify(_2));
            return 0 === buf.length ? '{}' : '{' + buf.join(',') + '}';
        }
        PSS.$stringify = $stringify;
        function $handle(type, message) {
            // TODO
            return 0;
        }
        PSS.$handle = $handle;
        PSS.$descriptor = {
            $fdf: ['1'],
            '1': { t: 3, m: 2, a: 0, $: 'p0', $n: 'TODO name for display' },
            '2': { t: 0, m: 2, a: 0, $: 'l', $n: 'TODO name for display', d: ds.PS.$descriptor },
            $: {
                p0: 1,
                l: 2
            },
            $handle: $handle
        };
    })(PSS = ps.PSS || (ps.PSS = {}));
})(ps || (ps = {}));
//# sourceMappingURL=index.js.map